import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { projects, getProject } from "@/content/projects";
import { ProjectVisual } from "@/components/ui/project-visual";

export function generateStaticParams() { return projects.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const project = getProject(slug); return project ? { title: `${project.title} | Softbridge Solutions`, description: project.summary } : {}; }

export default async function ProjectPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const project = getProject(slug);
  if (!project) notFound();
  return <main className="pb-28 pt-40"><div className="container-shell"><div className="grid gap-10 lg:grid-cols-[1.3fr_.7fr] lg:items-end"><div><p className="eyebrow text-black/45">{project.category} / {project.year}</p><h1 className="mt-7 text-[clamp(5rem,13vw,12rem)] font-semibold leading-[.78] tracking-[-.085em]">{project.title}</h1></div><p className="max-w-lg text-xl leading-snug tracking-[-.025em] text-black/65">{project.summary}</p></div><ProjectVisual tone={project.tone} title={project.title} className="mt-16 aspect-[16/9]"/><div className="mt-20 grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow text-black/42">Project details</p><dl className="mt-6 space-y-5 text-sm"><div className="border-t hairline pt-4"><dt className="text-black/42">Client</dt><dd className="mt-1 font-semibold">{project.client}</dd></div><div className="border-t hairline pt-4"><dt className="text-black/42">Location</dt><dd className="mt-1 font-semibold">{project.location}</dd></div><div className="border-t hairline pt-4"><dt className="text-black/42">Services</dt><dd className="mt-1 font-semibold">{project.services.join(" · ")}</dd></div></dl></div><div><section className="border-t hairline py-10"><p className="eyebrow text-black/42">Challenge</p><p className="mt-6 text-3xl leading-tight tracking-[-.04em] md:text-5xl">{project.challenge}</p></section><section className="border-t hairline py-10"><p className="eyebrow text-black/42">Solution</p><p className="mt-6 text-3xl leading-tight tracking-[-.04em] md:text-5xl">{project.solution}</p></section><section className="border-t hairline py-10"><p className="eyebrow text-black/42">Impact</p><ul className="mt-7">{project.impact.map((item, i) => <li key={item} className="grid grid-cols-[42px_1fr] border-b hairline py-5"><span className="font-mono text-[10px] text-black/40">0{i + 1}</span><span className="text-xl">{item}</span></li>)}</ul></section><blockquote className="mt-10 border-l-4 border-signal bg-[#0c1412] p-8 text-[#f4f5ef] md:p-14"><p className="text-4xl font-medium leading-tight tracking-[-.045em] md:text-6xl">“{project.quote}”</p></blockquote></div></div></div></main>;
}
