"use client";
import { useMemo, useState } from "react";
import { SlidersHorizontal, X } from "lucide-react";
import type { Product } from "@/types/commerce";
import { ProductGrid } from "@/components/commerce/product-grid";
import { Button } from "@/components/ui/button";
export function ShopClient({ initialProducts }: { initialProducts: Product[] }) {
  const [category,setCategory]=useState("All"); const [sort,setSort]=useState("featured"); const [query,setQuery]=useState(""); const [filters,setFilters]=useState(false);
  const categories=["All",...Array.from(new Set(initialProducts.map((p)=>p.category)))];
  const filtered=useMemo(()=>{ let result=initialProducts.filter((p)=>(category==="All"||p.category===category)&&p.name.toLowerCase().includes(query.toLowerCase())); if(sort==="price-asc") result=[...result].sort((a,b)=>a.price-b.price); if(sort==="price-desc") result=[...result].sort((a,b)=>b.price-a.price); if(sort==="new") result=[...result].sort((a,b)=>a.id.localeCompare(b.id)); return result; },[category,sort,query,initialProducts]);
  return <section className="py-8"><div className="mb-8 flex flex-col gap-4 border-b pb-5 lg:flex-row lg:items-end lg:justify-between"><div className="flex flex-wrap gap-2">{categories.map((item)=><button key={item} onClick={()=>setCategory(item)} className={`border px-4 py-2 text-xs uppercase tracking-[.12em] ${category===item?"bg-[var(--foreground)] text-[var(--background)]":""}`}>{item}</button>)}</div><div className="flex gap-3"><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search pieces" className="min-w-0 flex-1 border bg-transparent px-4 py-2 text-sm outline-none lg:w-56"/><select value={sort} onChange={(e)=>setSort(e.target.value)} className="border bg-transparent px-3 py-2 text-sm"><option value="featured">Featured</option><option value="new">Newest</option><option value="price-asc">Price low</option><option value="price-desc">Price high</option></select><Button variant="outline" size="sm" onClick={()=>setFilters(!filters)}><SlidersHorizontal size={15}/>Filters</Button></div></div>{filters?<div className="mb-8 grid gap-5 border p-5 md:grid-cols-4"><div><p className="eyebrow">Size</p><div className="mt-3 flex gap-2">{["XS","S","M","L","XL"].map((s)=><button key={s} className="border px-3 py-2 text-xs">{s}</button>)}</div></div><div><p className="eyebrow">Color</p><div className="mt-3 flex gap-2"><span className="size-7 rounded-full bg-black"/><span className="size-7 rounded-full bg-[#e9e3d8]"/><span className="size-7 rounded-full bg-[#9a3b2a]"/></div></div><div><p className="eyebrow">Availability</p><label className="mt-3 flex gap-2 text-sm"><input type="checkbox"/>In stock</label></div><button className="self-start justify-self-end" onClick={()=>setFilters(false)}><X/></button></div>:null}<div className="mb-5 flex justify-between text-sm text-[var(--muted)]"><span>{filtered.length} pieces</span><span>{category}</span></div>{filtered.length?<ProductGrid products={filtered}/>:<div className="grid min-h-80 place-items-center border"><div className="text-center"><p className="text-xl">No pieces match this edit.</p><button className="mt-4 underline" onClick={()=>{setQuery("");setCategory("All")}}>Reset filters</button></div></div>}</section>;
}
