import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ChevronDown } from "lucide-react";
import { getProduct, products } from "@/data/products";
import { formatPrice } from "@/lib/utils";
import { AddToCart } from "@/components/commerce/add-to-cart";
import { ProductGrid } from "@/components/commerce/product-grid";
export default async function ProductPage({ params }: { params: Promise<{slug:string}> }) { const {slug}=await params; const product=getProduct(slug); if(!product)notFound(); const related=products.filter((p)=>p.category===product.category&&p.id!==product.id).slice(0,4); return <main><div className="container-shell py-5"><Link href="/shop" className="text-xs uppercase tracking-[.14em]">← Shop</Link></div><section className="container-shell grid gap-8 lg:grid-cols-[1.35fr_.65fr]"><div className="grid gap-3 sm:grid-cols-2">{product.images.map((src,index)=><div key={`${src}-${index}`} className={`media-frame relative aspect-[3/4] ${index===2?"sm:col-span-2 sm:aspect-[16/9]":""}`}><Image src={src} alt={`${product.name} view ${index+1}`} fill priority={index<2} sizes="(max-width:1024px) 100vw, 45vw"/></div>)}</div><aside className="self-start py-5 lg:sticky lg:top-20"><p className="eyebrow">{product.collection} / {product.category}</p><h1 className="mt-4 text-4xl tracking-[-.04em] md:text-5xl">{product.name}</h1><div className="mt-4 flex gap-3"><span>{formatPrice(product.price)}</span>{product.compareAtPrice?<span className="text-[var(--muted)] line-through">{formatPrice(product.compareAtPrice)}</span>:null}</div><p className="mt-6 leading-7 text-[var(--muted)]">{product.description}</p><div className="mt-8"><AddToCart product={product}/></div><div className="mt-8 divide-y border-y">{[["Details",product.material],["Fit",product.fit],["Delivery & returns","Free standard delivery over ₺5,000. Returns accepted within 14 days."]].map(([title,copy])=><details key={title} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between"><span>{title}</span><ChevronDown size={17} className="transition group-open:rotate-180"/></summary><p className="pt-4 text-sm leading-6 text-[var(--muted)]">{copy}</p></details>)}</div></aside></section><section className="section-space container-shell"><div className="mb-10 flex justify-between border-t pt-5"><p className="eyebrow">Related forms</p><Link href="/shop">View all</Link></div><ProductGrid products={related}/></section></main> }
