"use client";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
const schema=z.object({email:z.email(),firstName:z.string().min(2),lastName:z.string().min(2),address:z.string().min(5),city:z.string().min(2),postal:z.string().min(4),phone:z.string().min(7),delivery:z.enum(["standard","express"])});type Values=z.infer<typeof schema>;
export function CheckoutForm(){const {register,handleSubmit,formState:{errors}}=useForm<Values>({resolver:zodResolver(schema),defaultValues:{delivery:"standard"}});return <form onSubmit={handleSubmit(()=>toast.success("Demo order validated"))} className="mt-12 grid gap-8 lg:grid-cols-[1fr_360px]"><div className="grid gap-8"><fieldset className="grid gap-4 border p-6"><legend className="px-2 text-lg">Contact</legend><Input label="Email" error={errors.email?.message}><input type="email" {...register("email")}/></Input><Input label="Phone" error={errors.phone?.message}><input {...register("phone")}/></Input></fieldset><fieldset className="grid gap-4 border p-6 sm:grid-cols-2"><legend className="px-2 text-lg">Delivery address</legend><Input label="First name" error={errors.firstName?.message}><input {...register("firstName")}/></Input><Input label="Last name" error={errors.lastName?.message}><input {...register("lastName")}/></Input><Input label="Address" error={errors.address?.message} className="sm:col-span-2"><input {...register("address")}/></Input><Input label="City" error={errors.city?.message}><input {...register("city")}/></Input><Input label="Postal code" error={errors.postal?.message}><input {...register("postal")}/></Input></fieldset><fieldset className="grid gap-3 border p-6"><legend className="px-2 text-lg">Delivery</legend><label className="flex justify-between border p-4"><span><input type="radio" value="standard" {...register("delivery")}/> Standard / 2–4 days</span><span>Free</span></label><label className="flex justify-between border p-4"><span><input type="radio" value="express" {...register("delivery")}/> Express / 1–2 days</span><span>₺190</span></label></fieldset></div><aside className="h-fit border p-6"><h2 className="text-xl">Payment</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Provider fields are intentionally represented as a secure integration boundary.</p><div className="mt-6 grid gap-4"><input className="border bg-transparent p-3" placeholder="Card number"/><div className="grid grid-cols-2 gap-3"><input className="border bg-transparent p-3" placeholder="MM / YY"/><input className="border bg-transparent p-3" placeholder="CVC"/></div></div><Button className="mt-6 w-full">Validate demo order</Button></aside></form>}
function Input({label,error,children,className=""}:{label:string;error?:string;children:React.ReactNode;className?:string}){return <label className={`grid gap-2 text-sm ${className}`}><span>{label}</span><span className="[&>input]:w-full [&>input]:border [&>input]:bg-transparent [&>input]:p-3 [&>input]:outline-none">{children}</span>{error?<span className="text-xs text-[var(--accent)]">Required field</span>:null}</label>}
